language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/
  - php tests/simple-profile.php

after_script:
 - php vendor/bin/coveralls -v

matrix:
  allow_failures:
